FROM node:latest

# Installing libvips-dev for sharp Compatibility
RUN apt-get update && apt-get install -y \
    build-essential gcc autoconf automake zlib1g-dev libpng-dev nasm bash libvips-dev

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json package-lock.json ./
RUN npm config set fetch-retry-maxtimeout 600000 -g
RUN npm install --no-optional && npm cache clean --force
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
RUN chown -R node:node /opt/app
USER node
RUN ["npm", "run", "build"]

EXPOSE 1337
CMD ["npm", "run", "develop"]
